### ISSUE TITLE
[TASK]: Documentation for deliverable 1

### ISSUE THREAD

**Issue by Aniol0012** [Computer-Engineering-UdL/Game-Management#26]
## TO-DO

- [x] Update the database model for the first deliverable.
- [x] Upload the deployment documentation to the repo.
- [x] Make the first deliverable of documentation on LaTeX. This must include:
     - [x] Project explaining.
     - [x] Additional comments about the application.
     - [x] DB model.
     - [x] Repo link.
- [x] Upload the first deliverable documentation to the repository.
- [x] Ensure README instructions are correct and functional.
- [x] Publish the release of the first deliverable

### Priority

High
